### ISSUE TITLE
File download error: 'mvhd' atom could not be found

### ISSUE THREAD

**Issue by tristansinclair** [NotTobi/soundcloud-dl#11]
[console-export-2021-1-3_20-3-27.txt](https://github.com/NotTobi/soundcloud-dl/files/5762974/console-export-2021-1-3_20-3-27.txt)

Certain files are unable to be downloaded. I was trying to sort through the error and look at possible resolutions but it appears to be an issue potentially with the file that is downloading itself. I think the file does not have a mvhd atom in the file. Would there be a fix to exclude the metadata in the mvhd atom and still proceed with creating the file? I'm still very on the surface level of how this plugin works but that is the little I was able to pick up on!

**Comment by tristansinclair** [comment]
After looking again, the issue appears to be there isn't a moov atom on the file I was trying to download. Is there a way around this?

**Comment by NotTobi** [comment]
Hi, thanks for reaching out!
I've just published a new version (v1.9.1) which should recover from errors related to setting the metadata and automatically download the file without metadata.
I do not have Soundcloud Pro at the moment, so I can't test if this will work correctly myself. Please reach out to me again if this works for you!

**Comment by NotTobi** [comment]
I'm closing this issue, due to lack of response and am considering this bug as fixed.
Feel free to re-open, if something comes up!
