### ISSUE TITLE
Downloaded .m4a files are unplayable/corrupted.

### ISSUE THREAD

**Issue by whatsupimr** [NotTobi/soundcloud-dl#2]
So the plugin works perfectly to retrieve and download the higher quality .m4a files, but there's one problem. The files are unplayable/corrupted in anything besides VLC. Anyone else have the same problem?
![Capture (2)](https://user-images.githubusercontent.com/23161744/80468454-6cfede80-88fc-11ea-8cda-810b3abd26b8.PNG)

**Comment by NotTobi** [comment]
I'm pretty sure I know what's causing this. Currently we are writing tags to it in the ID3v2 format, but m4a does not use this format. So it somehow work, but that it is working is more of like a bug or misbehavior of VLC in this case. I just quickly hacked together the HQ audio support, I know see that it is causing troubles for others. I planned on investigating why the artwork was not correctly set for m4a. I will look into it in the near future. I'm kind of busy right now though, so if you are fine with the LQ version you can disable the download of the HQ version in the add-on options (how to do this is documented in the README.md file).
Sorry for the inconvenience!

**Comment by cD3k** [comment]
thank you!

**Comment by NotTobi** [comment]
I just published a new version, that should fix this issue. Cover Art should now also be set correctly for .m4a files.
I don't own a Windows machine, so I'm not 100% certain it will work there as well.
Could you please test this new version and give me feedback, whether it is working or not. Make sure you're using version 1.4.0 or a newer version.
For reference, could you maybe also tell me which programs you tested with? (you mentioned anything besides VLC does not work, but it would be nice to have some concrete examples)

**Comment by whatsupimr** [comment]
Thank you so much for the quick responses! Cover art and all tags are set perfectly now, and the files are now playable with Groove Music, VLC, and Windows Media Player. Unfortunately, there is one more small problem. The files don't seem to have any track length metadata, so the progress bars on the bottom of Groove, VLC, etc. don't move. See pics. 

![Groove Music](https://user-images.githubusercontent.com/23161744/80761632-283f9700-8af8-11ea-9046-b95c05f9f545.PNG)
![VLC](https://user-images.githubusercontent.com/23161744/80761635-28d82d80-8af8-11ea-8e8c-334e6c23be0b.PNG)
![WMP](https://user-images.githubusercontent.com/23161744/80761636-28d82d80-8af8-11ea-9b98-5644d6264852.PNG)

**Comment by tobias-tengler** [comment]
Glad to hear it's (partially) working. :)
I don't set the length explicitly myself, I assumed soundcloud would do that... Let me look into it tomorrow!

**Comment by NotTobi** [comment]
Glad to hear it's (partially) working. :)
I don't set the length explicitly myself, I assumed soundcloud would do that... Let me look into it tomorrow!

**Comment by NotTobi** [comment]
I just published a new version (1.4.1), which should set the duration correctly for .m4a files. I also did some refactoring around the mp4TagWriter, so it can be easily extended in the future. Please give feedback, if this fixes your issue. I tested with VLC and the duration was correctly set for me.

**Comment by whatsupimr** [comment]
It works perfectly! Thank you so much for your super quick responses / updates!

**Comment by NotTobi** [comment]
Nice, glad to hear! :)
Could you please rate the extension [here](https://addons.mozilla.org/en-US/firefox/addon/soundcloud-dl/), if you have time!? I really put in an effort, but it still has relatively small download/review numbers. Sharing it would be awesome too, but I don't want to ask too much.
Have a nice day and enjoy the extension :)
