### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by eugene-za** [NotTobi/soundcloud-dl#23]
Cyrillic characters are removed from the title.

There is example page with cyrillic letters https://soundcloud.com/5vymir/

I think it happens on this line https://github.com/NotTobi/soundcloud-dl/blob/fc42488d918c135c80199d46e7565a0198d74bfc/src/metadataExtractor.ts#L375. You can probably add the cyrillic range "а-я" to the regex, or better use something like this "[^\p{L}|\p{N}]" for support alphabets of any language. 
I can't test my guess, so I'm sorry if I'm wrong and taking you down the wrong path. 

Thank you for your work. Good luck to you :)

**Comment by NotTobi** [comment]
I just released a new version (v1.11.0) that should be live any minute now and include support for Cyrillic letters and all other Unicode letters.
I'm closing this for now, feel free to re-open, if there are any more issues related to this :)
