### ISSUE TITLE
Cannot download file

### ISSUE THREAD

**Issue by vklymchuk** [NotTobi/soundcloud-dl#25]
Hi!
[Link to file](https://soundcloud.com/aamirrnb/akon-i-wanna-love-you-cover-remix)
[console-export-2021-6-28_9-54-40.txt](https://github.com/NotTobi/soundcloud-dl/files/6724081/console-export-2021-6-28_9-54-40.txt)

**Comment by NotTobi** [comment]
This should be fixed with v1.12.0 I've just released. I'm closing this issue, feel free to re-open if the issue persists!

Also please consider giving the [extension a positive review](https://addons.mozilla.org/en-US/firefox/addon/soundcloud-dl/) :heart:
