### ISSUE TITLE
Og Files

### ISSUE THREAD

**Issue by freesoui** [NotTobi/soundcloud-dl#28]
Hey! This is more or less not really an issue, i love this add on, but is there anyway you could get it could download the og file?
I don't mean when the account owner has enabled downloads btw.

I was told there used to be a og file method. Idk if it's possible anymore...?

**Comment by NotTobi** [comment]
I don't think what you're describing is possible anymore. I've checked various sources, but there doesn't seem to be an ability to download the original version of _every_ track. Sorry!

If you like the add-on, please make sure to leave a [positive review](https://addons.mozilla.org/firefox/addon/soundcloud-dl/) :heart:
