### ISSUE TITLE
Downloads Hang, never resolve

### ISSUE THREAD

**Issue by GratefulForUpdatedLaunchy** [NotTobi/soundcloud-dl#3]
![Untitled](https://user-images.githubusercontent.com/57156167/81845444-9dcc4e00-9561-11ea-8fdd-ef8a00d4e5c5.png)

![Untitled2](https://user-images.githubusercontent.com/57156167/81845451-9f961180-9561-11ea-830b-3ce38e5dacad.png)

'Toolbox - error occured'
about:devtools-toolbox?type=extension&amp;id={c7a839e7-7086-4021-8176-1cfcb7f169ce}

**Comment by GratefulForUpdatedLaunchy** [comment]
I double checked the extension id matched

![Untitled](https://user-images.githubusercontent.com/57156167/81845778-192dff80-9562-11ea-8226-bcf3e468fdba.png)

**Comment by NotTobi** [comment]
Okay, that's weird. Can you try navigating to the about:debugging webpage. In the left pane click on extensions and locate this extension in the list. In the top right there should be an inspect button. Click on it and it should take you to the page I initially wanted you to visit. Please take the screenshot there then.
Also you are not perhaps using a private firefox window. I myself had issues with downloading in private mode...

**Comment by GratefulForUpdatedLaunchy** [comment]
I double checked the extension id matched

**Comment by GratefulForUpdatedLaunchy** [comment]
![image](https://user-images.githubusercontent.com/57156167/81846449-2697b980-9563-11ea-8a32-adf24b15eebf.png)

**Comment by GratefulForUpdatedLaunchy** [comment]
So it looks like enabling Firefox Strict Tracking Protection and setting all 3rd party cookies to be blocked could be the issue?  Potentially also uBlock Origin is blocking the process?

I disabled FF tracking protection, and uninstalled ublock origin.  Then I refreshed the SoundCloud page.

Download is not resolving still.

Notice 'Error: filename must not be an absolute path' in console.
Updating download-without-prompt to false

![image](https://user-images.githubusercontent.com/57156167/81847147-3d8adb80-9564-11ea-81dd-36435059ce07.png)


That seemed to fix the issue.

I can go ahead and use this Firefox profile for my SC downloading.

**Comment by GratefulForUpdatedLaunchy** [comment]
I am noticing 

"can't access lexical declaration `downloadId' before initialization"

![image](https://user-images.githubusercontent.com/57156167/81847443-a96d4400-9564-11ea-8085-dc8eaddeadc2.png)

**Comment by GratefulForUpdatedLaunchy** [comment]
Here is the console from my standard installation.
As you will notice in the top right hand corner, I have a fair amount of extensions enabled. Lots to enhance privacy.

![image](https://user-images.githubusercontent.com/57156167/81847989-7d05f780-9565-11ea-850e-66405555a69d.png)

SC-DL did not seem to fair very well in that environment.

**Comment by GratefulForUpdatedLaunchy** [comment]
I re-enabled uBlock, and FF's Tracking Protection settings to strict.  Downloading works.  It appears I was being impatient. There is a delay of 60-180 seconds for the download to begin.

On my standard FF installation the downloads fail.

I appreciate your help.

Thanks for teaching me about 'about:debugging'

**Comment by NotTobi** [comment]
ublock origin should not be the culprit, I use it as well. I haven't used tracking protection yet though. Those are some good insights you delivered! I'm currently pretty busy, but I will take a look on the weekend. Sorry it is not working for you out of the box. That's always annoying! I think we can get this resolved though! :)

**Comment by NotTobi** [comment]
Abou the delay: That's because I download the file in memory in the background, since I need to be able to set metadata, before it is downloaded to your system. So it is actually downloading in the background and when the download starts for you in FF, it's just flushing the file in memory to your disk. That's why I added the 'Downloading' text on the button, as a form of indicator. This could be better documented though ^^

**Comment by GratefulForUpdatedLaunchy** [comment]
No worries.  It pretty much is working out of the box.  I didn't realize that the file was being downloaded in the background.   This makes sense.  When there was no visual representation of this outside of the 'downloading' text, with no progress, I presumed nothing was happening.
On 5/13/2020 10:39:44 PM, definitely not tobi <notifications@github.com> wrote:
Abou the delay: That's because I download the file in memory in the background, since I need to be able to set metadata, before it is downloaded to your system. So it is actually downloading in the background and when the download starts for you in FF, it's just flushing the file in memory to your disk. That's why I added the 'Downloading' text on the button, as a form of indicator. This could be better documented though ^^

**Comment by GratefulForUpdatedLaunchy** [comment]
Hello NotTobi,

I am attempting to download a track.  The title of the track contains a ':' which is an illegal character in windows.  Here's the URL of the track
https://soundcloud.com/marbs/mind-of-marbs-volume-004

Here's the console screen:
![Untitled](https://user-images.githubusercontent.com/57156167/82113116-e98a1d80-9742-11ea-94ff-83ae4a63abf2.png)

**Comment by NotTobi** [comment]
No, I was actually already replacing the colon. The issue is that after I replace the colon with an empty string, there were two spaces directly after each other. I changed it to trim consecutive white-space to a single space. Fix should be up in a few minutes (v1.5.7).
I'm also looking into adding a progress indicator in form of a progress bar today! :)

**Comment by GratefulForUpdatedLaunchy** [comment]
Sweet deal ✌

Jordan Hampton
  +995 551 588 894
  +1 (714) 225-9923 (Signal, Telegram)
On 5/16/2020 11:56:06 AM, definitely not tobi <notifications@github.com> wrote:
No, I was actually already replacing the colon. The issue is that after I replace the colon with an empty string, there were two spaces directly after each other. I changed it to trim consecutive white-space to a single space. Fix should be up in a few minutes (v1.5.7).
I'm also looking into adding a progress indicator in form of a progress bar today! :)

**Comment by tobias-tengler** [comment]
I added a progress bar to the buttons. Version should be up in a few minutes (v1.6.0).
Let me know, if this better for you :)
I will now also look into your bug, related to the other extensions and FF's tracking protection.
Also, since you're so privacy focused, I would edit your reply, to get your phone number out of there ^^

**Comment by NotTobi** [comment]
I added a progress bar to the buttons. Version should be up in a few minutes (v1.6.0).
Let me know, if this better for you :)
I will now also look into your bug, related to the other extensions and FF's tracking protection.
Also, since you're so privacy focused, I would edit your reply, to get your phone number out of there ^^

**Comment by GratefulForUpdatedLaunchy** [comment]
Right! These replies from my email get posted to the git page 🤡


On 5/16/2020 2:55:46 PM, definitely not tobi <notifications@github.com> wrote:
I added a progress bar to the buttons. Version should be up in a few minutes (v1.6.0).
Let me know, if this better for you :)
I will now also look into your bug, related to the other extensions and FF's tracking protection.
Also, since you're so privacy focused, I would edit your reply, to get your phone number out of there ^^

**Comment by GratefulForUpdatedLaunchy** [comment]
My standard installation is now working with the downloads.  Maybe the new update?

**Comment by GratefulForUpdatedLaunchy** [comment]
I'll close this issue.  I appreciate you helping out and all of your time.  This is a fantastic addon 😎
