### ISSUE TITLE
Corrupt m4a

### ISSUE THREAD

**Issue by Catarax** [NotTobi/soundcloud-dl#37]
Didn't got a lot of issues except for some tracks :

Theses tracks can't be played at all when downloaded with a premium or free account :
https://soundcloud.com/djsnake/best-of-both-worlds
https://soundcloud.com/djsnake/secret-room-livestream

**Comment by NotTobi** [comment]
There's nothing I can do about this for certain tracks as explained [here](https://github.com/NotTobi/soundcloud-dl/issues/16#issuecomment-819001891)
