### ISSUE TITLE
All files download as mp3 not m4a now

### ISSUE THREAD

**Issue by tristansinclair** [NotTobi/soundcloud-dl#6]
After the most recent update I'm only able to download mp3 rather than m4a. Is there a fix for this or a way I can go back to the old version?

**Comment by NotTobi** [comment]
I no longer own SoundCloud Go, so I couldn't test the new version with m4a. I was hoping that it would just work, but doesn't seem like it :/
I will re-buy it tomorrow and take a look again. Sorry for the inconvenience!

**Comment by tristansinclair** [comment]
All good man! Also the new HLS download is huge! Ya, but if you want to look at it, basically stuff that isn't HLS seems to always downloads as mp3 now rather than the m4a. Also idk if it's possible to get m4a out of the HLS but those are always mp3 as well. Appreciate the plugin though seriously it's been awesome for me. You totally changed the game with this one!!

**Comment by NotTobi** [comment]
Glad to hear that you like it! :)
I guess I'll be able to reproduce it easily tomorrow, but just to be sure, could you link me a track that previously downloaded for you as .m4a and now no longer does? Thanks a lot!

**Comment by NotTobi** [comment]
Just published a new version (v1.7.1) that should fix this.
I'm closing this issue. If you still have problems, feel free to comment again!
